### ISSUE TITLE
Update to pm5

### ISSUE THREAD

**Issue by ghost** [cosmicnebula200/SellMe#8]
It would be a good plugin in pm5

**Comment by cosmicnebula200** [comment]
Hello @SrBanYT2143,

Thanks for the suggestion, but I dont think so doing this will be a great idea as of today (due to the fact that none of the Economy Providers are actually updated to PM5). A sell plugin without an actual economy plugin would be meaningless and hence will not be something I would put my time on updating.

PM5 isnt that much code breaking updating to it shouldnt take as long as pm3->pm4 updates so I am sure it wont be long for the economy plugins to be updated once PM5 is officially out. 

Tbh I am planning on to continue to maintain this even for PM5 . Even if one of the Economy Providers (EconomyAPI/BedrockEconomy/Capital) is updated to PM5 I will also be dropping a branch just to support PM5.

**Comment by ghost** [comment]
there was not much change in the economy plugin, at least in "BedrockEconomy" it is working perfectly in pocketmine 5 after api change in plugin.yml

I understand your side, I use this plugin on pocketmine 4 but I'm updating my server so when pocketmine 5 launches I open my server peacefully. No and many who agree.

**Comment by ghost** [comment]
Could open a branch for pocketmine 5

**Comment by cosmicnebula200** [comment]
> Could open a branch for pocketmine 5

Sure! I will prolly do it in a few weeks
